### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by liuqingl** [zjnGitHub/AutoStarRail#13]
main.py打开就闪退

**Comment by zjnGitHub** [comment]
这个问题是第一次有人遇到，能否给出更详细的内容？比如是否有报错，依赖是否正确安装，python版本是多少方便我定位错误。
目前python是要3.11启动

**Comment by liuqingl** [comment]
> Python 3.11.0rc2 (main, Sep 11 2022, 20:22:52) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

============== RESTART: F:\AutoStarRail\AutoStarRail-main\main.py ==============
Traceback (most recent call last):
  File "F:\AutoStarRail\AutoStarRail-main\main.py", line 5, in <module>
    from PySide6.QtGui import QIcon, QPixmap
ModuleNotFoundError: No module named 'PySide6'

requirements.txt文件里写有PySide6==6.4.3啊

**Comment by liuqingl** [comment]
> 这个问题是第一次有人遇到，能否给出更详细的内容？比如是否有报错，依赖是否正确安装，python版本是多少方便我定位错误。 目前python是要3.11启动

============== RESTART: F:\AutoStarRail\AutoStarRail-main\main.py ==============
Traceback (most recent call last):
File "F:\AutoStarRail\AutoStarRail-main\main.py", line 5, in
from PySide6.QtGui import QIcon, QPixmap
ModuleNotFoundError: No module named 'PySide6'

requirements.txt文件里写有PySide6==6.4.3啊

**Comment by liuqingl** [comment]
> 这个问题是第一次有人遇到，能否给出更详细的内容？比如是否有报错，依赖是否正确安装，python版本是多少方便我定位错误。 目前python是要3.11启动

[requirements.txt](https://github.com/zjnGitHub/AutoStarRail/files/12293439/requirements.txt)

**Comment by zjnGitHub** [comment]
1. 再次使用`pip install -r requirements.txt`安装一边库
2. 直接使用`pip install XXX`，这个方法的问题就是可能会与其他的库不兼容,可以指定与requirements.txt一样的版本，具体指令自己上网搜

**Comment by liuqingl** [comment]
> 1. 再次使用`pip install -r requirements.txt`安装一边库
> 2. 直接使用`pip install XXX`，这个方法的问题就是可能会与其他的库不兼容,可以指定与requirements.txt一样的版本，具体指令自己上网搜

ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'F:\\AutoStarRail\\StarRailAssistant\\whl\\httpx_socks-0.7.7-py3-none-any.whl'

**Comment by liuqingl** [comment]
> 1. 再次使用安装一边库`pip install -r requirements.txt`
> 2. 直接使用，这个方法的问题就是可能会与其他的库不兼容，可以指定与requirements.txt一样的版本，具体指令自己上网搜`pip install XXX`


我从StarRailAssistant那重新下载了一遍httpx_socks-0.7.7-py3-none-any.whl然后尝试直接启动main.py

F:\AutoStarRail\AutoStarRail-main>pip3 install -r requirements.txt
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Processing f:\autostarrail\starrailassistant\whl\httpx_socks-0.7.7-py3-none-any.whl (from -r requirements.txt (line 47))
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'F:\\AutoStarRail\\StarRailAssistant\\whl\\httpx_socks-0.7.7-py3-none-any.whl'


F:\AutoStarRail\AutoStarRail-main>python ./main.py
Traceback (most recent call last):
  File "F:\AutoStarRail\AutoStarRail-main\main.py", line 8, in <module>
    from gui.main_window import MainWindow
  File "F:\AutoStarRail\AutoStarRail-main\gui\main_window.py", line 5, in <module>
    from qframelesswindow import FramelessMainWindow, FramelessWindow
ModuleNotFoundError: No module named 'qframelesswindow'

**Comment by zjnGitHub** [comment]
这些全是你电脑上配置的问题，你改下镜像源就行了，你要学会优先查百度等搜索引擎

**Comment by liuqingl** [comment]
> 



> 这些全是你电脑上配置的问题，你改下镜像源就行了，你要学会优先查百度等搜索引擎

是cmd里改成国内的镜像源吗？我也不知道要搜索什么才能解决这个问题

**Comment by liuqingl** [comment]
> > 
> 
> > 这些全是你电脑上配置的问题，你改下镜像源就行了，你要学会优先查百度等搜索引擎
> 
> 是cmd里改成国内的镜像源吗？我也不知道要搜索什么才能解决这个问题

我按照百度更改镜像源后还是一样的报错

**Comment by liuqingl** [comment]
> 这些全是你电脑上配置的问题，你改下镜像源就行了，你要学会优先查百度等搜索引擎

F:\AutoStarRail\AutoStarRail-main>pip install -i https://pypi.doubanio.com/simple/ --trusted-host pypi.doubanio.com --target=F:\AutoStarRail\AutoStarRail-main httpx_socks-0.7.7-py3-none-any.whl
WARNING: Requirement 'httpx_socks-0.7.7-py3-none-any.whl' looks like a filename, but the file does not exist
Looking in indexes: https://pypi.doubanio.com/simple/
Processing f:\autostarrail\autostarrail-main\httpx_socks-0.7.7-py3-none-any.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'F:\\AutoStarRail\\AutoStarRail-main\\httpx_socks-0.7.7-py3-none-any.whl'

**Comment by liuqingl** [comment]
> > 这些全是你电脑上配置的问题，你改下镜像源就行了，你要学会优先查百度等搜索引擎
> 
> F:\AutoStarRail\AutoStarRail-main>pip install -i https://pypi.doubanio.com/simple/ --trusted-host pypi.doubanio.com --target=F:\AutoStarRail\AutoStarRail-main httpx_socks-0.7.7-py3-none-any.whl WARNING: Requirement 'httpx_socks-0.7.7-py3-none-any.whl' looks like a filename, but the file does not exist Looking in indexes: https://pypi.doubanio.com/simple/ Processing f:\autostarrail\autostarrail-main\httpx_socks-0.7.7-py3-none-any.whl ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'F:\AutoStarRail\AutoStarRail-main\httpx_socks-0.7.7-py3-none-any.whl'

F:\AutoStarRail\AutoStarRail-main>pip3 install -r requirements.txt
Looking in indexes: https://pypi.mirrors.ustc.edu.cn/simple
Processing f:\autostarrail\starrailassistant\whl\httpx_socks-0.7.7-py3-none-any.whl (from -r requirements.txt (line 47))
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'F:\\AutoStarRail\\StarRailAssistant\\whl\\httpx_socks-0.7.7-py3-none-any.whl'
更改镜像源还是一样的报错

**Comment by zjnGitHub** [comment]
等我下一次更新吧，这是requirements中有本地文件，你如果找的到就直接删了就行，如果找不到就等我下一次更新
