### ISSUE TITLE
无法安装依赖

### ISSUE THREAD

**Issue by half-drop** [zjnGitHub/AutoStarRail#15]
![image](https://github.com/zjnGitHub/AutoStarRail/assets/39797906/4c07a264-8a4d-4018-9018-1e5502d28a39)

**Comment by zjnGitHub** [comment]
把F盘的路径删了，我忘记给他删掉了，下个版本会更新的。
只需要把带有@ file:///F:/AutoStarRail/XXX 的删掉就行，或者等下一个版本。

**Comment by half-drop** [comment]
我找了半天还是找不到在哪删...
