### ISSUE TITLE
拟造花萼部分似乎没有加上滚轮查找

### ISSUE THREAD

**Issue by WHU-WAKADA** [zjnGitHub/AutoStarRail#20]
在stamina.py中，Calyx类下的start函数中添加两行

        log.transmitRunLog(f"找图片")
        transmission_rect = search_transmission(cls.filename[calyx_name])

        if transmission_rect is None:
            transmission_rect = mouse_scroll_search(cls.filename[4], cls.filename[calyx_name])

        pyautogui.moveTo(transmission_rect)
        pyautogui.click()

**Comment by zjnGitHub** [comment]
好的，我下一个版本就加上
