### ISSUE TITLE
键位设置

### ISSUE THREAD

**Issue by fjf010223** [zjnGitHub/AutoStarRail#27]
锄大地时默认按m打开地图，我游戏里改了地图按键，试着改了下config.json文件里的openmap的键位，但是依然还是按m打开地图，可以支持改键吗

**Comment by zjnGitHub** [comment]
修改的是AutoStarRail下的config还是StarRailAssistant下的config

**Comment by zjnGitHub** [comment]
测试后发现修改open_map依旧有效，请修改StarRailAssistant下的config.json
